#!/usr/bin/env bash
# PreToolUse (Edit|Write|MultiEdit) — refuse or escalate writes to files that
# should never be edited by hand.
#
# permissions.deny already blocks *reading* secrets. This covers *writing*:
# generated output, vendored code, and config that governs the agent itself.

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
# shellcheck source=../scripts/lib/common.sh
. "$SCRIPT_DIR/../scripts/lib/common.sh"

INPUT="$(cc_hook_input)"
FILE="$(cc_json "$INPUT" '.tool_input.file_path')"
[ -z "$FILE" ] && FILE="$(cc_json "$INPUT" '.tool_input.path')"
[ -z "$FILE" ] && exit 0

# Compare on a repo-relative path so the patterns are stable.
REL="${FILE#"$CC_ROOT"/}"

deny() { cc_emit_deny "PreToolUse" "$1"; exit 0; }
ask()  { cc_emit_ask  "PreToolUse" "$1"; exit 0; }

case "$REL" in
  .env|.env.*|*/.env|*/.env.*)
    deny "Refused: '$REL' holds secrets and is never edited by the agent.
Add the variable to .env.example with a dummy value instead, and tell the user
which real value they need to set." ;;

  *.pem|*.key|*.p12|*.pfx|*/secrets/*|secrets/*)
    deny "Refused: '$REL' is credential material. It is never created or edited
here. See .claude/conventions/security.md." ;;

  */dist/*|dist/*|*/build/*|build/*|*/out/*|out/*|*.generated.*|*/__generated__/*)
    deny "Refused: '$REL' is build output or generated code.
Change the source or the generator and re-run it — hand edits are overwritten on
the next build and hide the real change from review." ;;

  vendor/*|*/vendor/*|node_modules/*|*/node_modules/*)
    deny "Refused: '$REL' is vendored/installed code. Patch upstream, pin a
different version, or use a documented patch mechanism." ;;

  *.lock|*lock.json|*/pnpm-lock.yaml|pnpm-lock.yaml|*/yarn.lock|yarn.lock)
    deny "Refused: '$REL' is a lockfile. Hand-editing one produces an install
that nobody else can reproduce. Run the package manager instead." ;;

  .githooks/*)
    ask "'$REL' is a managed git hook — it is regenerated by
.claude/scripts/install-git-hooks.sh, so an edit here will be silently lost.
Change preflight.sh or that installer instead. Continue anyway?" ;;

  .claude/settings.json|*/.claude/settings.json)
    ask "'$REL' governs permissions and hooks for everyone on this repo.
Changing it changes what the agent is allowed to do. Continue?" ;;
esac

exit 0
